<?php
/**
 * Author: Sergey Grigoriev
 */

class GrigorievCommon {

    const MINSK_BELARUS = '';

    const PERSON_ADDRESS = self::MINSK_BELARUS;
    const PERSON_PLACE_OF_BIRTH = self::MINSK_BELARUS;
    const PERSON_PHONE = '+375 29 767 57 81';
    const PERSON_EMAIL = 'sergey@grigoriev.eu';
    const PERSON_SKYPE = 'sergey.a.grigoriev';
    const PERSON_DATE_OF_BIRTH = '1984-07-14';
    const PERSON_HOMEPAGE = 'http://grigoriev.eu/';
    const PERSON_PERSON_UNIQUE_NAME = 'sergeygrigoriev';

    const EMPLOYER_BSUIR_CPI_HOMEPAGE = 'http://www.bsuir.by/';
    const EMPLOYER_BSUIR_CPI_ADDRESS = self::MINSK_BELARUS;
    const EMPLOYER_BSUIR_CPI_START_DATE = '2006-09-01';
    const EMPLOYER_BSUIR_CPI_END_DATE = '2008-08-31';
    const EMPLOYER_SAM_SOLUTIONS_BELARUS_COMPANY = 'SaM Solutions Belarus';
    const EMPLOYER_SAM_SOLUTIONS_BELARUS_HOMEPAGE = 'http://www.sam-solutions.com/';
    const EMPLOYER_SAM_SOLUTIONS_BELARUS_ADDRESS = self::MINSK_BELARUS;
    const EMPLOYER_SAM_SOLUTIONS_BELARUS_SSE_START_DATE = '2008-09-01';
    const EMPLOYER_SAM_SOLUTIONS_BELARUS_SSE_END_DATE = '2011-11-30';
    const EMPLOYER_SAM_SOLUTIONS_BELARUS_TL_START_DATE = '2011-12-01';
    const EMPLOYER_SAM_SOLUTIONS_BELARUS_TL_END_DATE = '0000-00-00';

    const EDUCATION_BSUIR_ADDRESS = self::MINSK_BELARUS;
    const EDUCATION_BSUIR_START_DATE = '2001-09-01';
    const EDUCATION_BSUIR_END_DATE = '2006-06-30';
    const EDUCATION_BSEU_ADDRESS = self::MINSK_BELARUS;
    const EDUCATION_BSEU_START_DATE = '2004-09-01';
    const EDUCATION_BSEU_END_DATE = '2008-06-30';

    const PROGRAMMING_LANGUAGE_JAVA = 'Java';
    const PROGRAMMING_LANGUAGE_JAVA_EXPERIENCE = '3';
    const PROGRAMMING_LANGUAGE_C = 'C';
    const PROGRAMMING_LANGUAGE_C_EXPERIENCE = '5';
    const PROGRAMMING_LANGUAGE_CPP = 'C++';
    const PROGRAMMING_LANGUAGE_CPP_EXPERIENCE = '2';
    const PROGRAMMING_LANGUAGE_OBJECTIVE_C = 'Objective-C';
    const PROGRAMMING_LANGUAGE_OBJECTIVE_C_EXPERIENCE = '1';
    const PROGRAMMING_LANGUAGE_CSHARP = 'C#';
    const PROGRAMMING_LANGUAGE_CSHARP_EXPERIENCE = '1';
    const PROGRAMMING_LANGUAGE_SQL = 'SQL';
    const PROGRAMMING_LANGUAGE_SQL_EXPERIENCE = '3';
    const PROGRAMMING_LANGUAGE_XML = 'XML';
    const PROGRAMMING_LANGUAGE_XML_EXPERIENCE = '3';
    const PROGRAMMING_LANGUAGE_PHP = 'PHP';
    const PROGRAMMING_LANGUAGE_PHP_EXPERIENCE = '3';
    const PROGRAMMING_LANGUAGE_JAVASCRIPT = 'JavaScript';
    const PROGRAMMING_LANGUAGE_JAVASCRIPT_EXPERIENCE = '1';

    const TECHNOLOGY_J2SE = 'J2SE';
    const TECHNOLOGY_J2SE_EXPERIENCE = '3';
    const TECHNOLOGY_J2EE = 'J2EE';
    const TECHNOLOGY_J2EE_EXPERIENCE = '1';
    const TECHNOLOGY_HIBERNATE = 'Hibernate';
    const TECHNOLOGY_HIBERNATE_EXPERIENCE = '2';
    const TECHNOLOGY_SPRING_FRAMEWORK = 'Spring Framework';
    const TECHNOLOGY_SPRING_FRAMEWORK_EXPERIENCE = '1';
    const TECHNOLOGY_SWING = 'Swing';
    const TECHNOLOGY_SWING_EXPERIENCE = '1';
    const TECHNOLOGY_APACHE_WICKET = 'Apache Wicket';
    const TECHNOLOGY_APACHE_WICKET_EXPERIENCE = '1';
    const TECHNOLOGY_JAVA_SERVLETS = 'Java Servlets';
    const TECHNOLOGY_JAVA_SERVLETS_EXPERIENCE = '1';
    const TECHNOLOGY_JSP = 'Java Server Pages (JSP)';
    const TECHNOLOGY_JSP_EXPERIENCE = '1';
    const TECHNOLOGY_APPLETS = 'Applets';
    const TECHNOLOGY_APPLETS_EXPERIENCE = '1';
    const TECHNOLOGY_JUNIT = 'JUnit';
    const TECHNOLOGY_JUNIT_EXPERIENCE = '3';
    const TECHNOLOGY_JNI = 'JNI';
    const TECHNOLOGY_JNI_EXPERIENCE = '1';
    const TECHNOLOGY_SOAP = 'SOAP';
    const TECHNOLOGY_SOAP_EXPERIENCE = '2';
    const TECHNOLOGY_CPP_STDLIB = 'C++ stdlib';
    const TECHNOLOGY_CPP_STDLIB_EXPERIENCE = '2';
    const TECHNOLOGY_COCOA_FRAMEWORK = 'Cocoa Framework';
    const TECHNOLOGY_COCOA_FRAMEWORK_EXPERIENCE = '1';
    const TECHNOLOGY_CARBONLIB = 'CarbonLib';
    const TECHNOLOGY_CARBONLIB_EXPERIENCE = '1';

    const OPERATING_SYSTEM_MS_WINDOWS = 'MS Windows';
    const OPERATING_SYSTEM_MS_WINDOWS_EXPERIENCE = '8';
    const OPERATING_SYSTEM_LINUX = 'Linux';
    const OPERATING_SYSTEM_LINUX_EXPERIENCE = '4';
    const OPERATING_SYSTEM_MACOS_X10 = 'Mac OS X 10';
    const OPERATING_SYSTEM_MACOS_X10_EXPERIENCE = '2';
    const OPERATING_SYSTEM_ANDROID = 'Android';
    const OPERATING_SYSTEM_ANDROID_EXPERIENCE = '1';

    const RDBMS_MSSQL = 'MS SQL';
    const RDBMS_MSSQL_EXPERIENCE = '2';
    const RDBMS_POSTGRESQL = 'PostgreSQL';
    const RDBMS_POSTGRESQL_EXPERIENCE = '2';
    const RDBMS_SQLITE = 'SQLite';
    const RDBMS_SQLITE_EXPERIENCE = '1';
    const RDBMS_MYSQL = 'MySQL';
    const RDBMS_MYSQL_EXPERIENCE = '1';
    const RDBMS_H2 = 'H2database';
    const RDBMS_H2_EXPERIENCE = '1';
    const RDBMS_ORACLE = 'Oracle';
    const RDBMS_ORACLE_EXPERIENCE = '1';

    const WEB_AND_APPLICATION_SERVER_APACHE_HTTP_SERVER = 'Apache HTTP Server';
    const WEB_AND_APPLICATION_SERVER_APACHE_HTTP_SERVER_EXPERIENCE = '3';
    const WEB_AND_APPLICATION_SERVER_APACHE_TOMCAT = 'Apache Tomcat';
    const WEB_AND_APPLICATION_SERVER_APACHE_TOMCAT_EXPERIENCE = '2';
    const WEB_AND_APPLICATION_SERVER_JBOSS_AS = 'JBoss AS';
    const WEB_AND_APPLICATION_SERVER_JBOSS_AS_EXPERIENCE = '1';
    const WEB_AND_APPLICATION_SERVER_JETTY = 'Jetty';
    const WEB_AND_APPLICATION_SERVER_JETTY_EXPERIENCE = '1';

    const CASE_AND_PROJECT_TOOL_SVN = 'SVN';
    const CASE_AND_PROJECT_TOOL_SVN_EXPERIENCE = '5';
    const CASE_AND_PROJECT_TOOL_IBM_CLEARCASE = 'IBM ClearCase';
    const CASE_AND_PROJECT_TOOL_IBM_CLEARCASE_EXPERIENCE = '3';
    const CASE_AND_PROJECT_TOOL_CVS = 'CVS';
    const CASE_AND_PROJECT_TOOL_CVS_EXPERIENCE = '2';
    const CASE_AND_PROJECT_TOOL_MS_PROJECT = 'MS Project';
    const CASE_AND_PROJECT_TOOL_MS_PROJECT_EXPERIENCE = '4';
    const CASE_AND_PROJECT_TOOL_HUDSON_JENKINS = 'Hudson/Jenkins';
    const CASE_AND_PROJECT_TOOL_HUDSON_JENKINS_EXPERIENCE = '2';
    const CASE_AND_PROJECT_TOOL_JIRA = 'Atlassian JIRA';
    const CASE_AND_PROJECT_TOOL_JIRA_EXPERIENCE = '4';
    const CASE_AND_PROJECT_TOOL_BUGZILLA = 'Bugzilla';
    const CASE_AND_PROJECT_TOOL_BUGZILLA_EXPERIENCE = '2';

    const IDE_ECLIPSE = 'Eclipse';
    const IDE_ECLIPSE_EXPERIENCE = '3';
    const IDE_MS_VISUAL_STUDIO = 'MS Visual Studio';
    const IDE_MS_VISUAL_STUDIO_EXPERIENCE = '5';
    const IDE_INTELLIJ_IDEA = 'IntelliJ IDEA';
    const IDE_INTELLIJ_IDEA_EXPERIENCE = '3';
    const IDE_INTELLIJ_PHPSTORM = 'IntelliJ PhpStorm';
    const IDE_INTELLIJ_PHPSTORM_EXPERIENCE = '1';
    const IDE_NETBEANS = 'NetBeans';
    const IDE_NETBEANS_EXPERIENCE = '1';
    const IDE_XCODE = 'XCode';
    const IDE_XCODE_EXPERIENCE = '1';

    const COURSE_AND_CERTIFICATE_SOFTWARE_REQUIREMENTS_DEVELOPMENT_AND_MANAGEMENT_AWARDED = 'dp Consulting';
    const COURSE_AND_CERTIFICATE_SOFTWARE_REQUIREMENTS_DEVELOPMENT_AND_MANAGEMENT_DATE = '2008-10-15';
    const COURSE_AND_CERTIFICATE_ESTIMATIONS_FOR_SOFTWARE_PROJECTS_AWARDED = 'dp Consulting';
    const COURSE_AND_CERTIFICATE_ESTIMATIONS_FOR_SOFTWARE_PROJECTS_DATE = '2011-01-10';
    const COURSE_AND_CERTIFICATE_IBM_RATIONAL_CLEARCASE_AWARDED = 'SaM Solutions Belarus';
    const COURSE_AND_CERTIFICATE_IBM_RATIONAL_CLEARCASE_DATE = '2011-03-11';
    const COURSE_AND_CERTIFICATE_GOETHE_ZERTIFIKAT_A2_TITLE = 'Goethe-Zertifikat A2: Start Deutsch 2';
    const COURSE_AND_CERTIFICATE_GOETHE_ZERTIFIKAT_A2_AWARDED = 'Goethe-Institut Minsk';
    const COURSE_AND_CERTIFICATE_GOETHE_ZERTIFIKAT_A2_DATE = '2012-06-11';
    const COURSE_AND_CERTIFICATE_AGILE_ENGINEERING_PRACTICES_AWARDED = 'XP Injection';
    const COURSE_AND_CERTIFICATE_AGILE_ENGINEERING_PRACTICES_DATE = '2012-10-27';
    const COURSE_AND_CERTIFICATE_TDD_IN_JAVA_AWARDED = 'Pragmatists';
    const COURSE_AND_CERTIFICATE_TDD_IN_JAVA_DATE = '2012-12-08';
    const COURSE_AND_CERTIFICATE_PRAGMATIC_TDD_AWARDED = 'SaM Solutions Belarus';
    const COURSE_AND_CERTIFICATE_PRAGMATIC_TDD_DATE = '2013-04-02';
    const COURSE_AND_CERTIFICATE_GOETHE_ZERTIFIKAT_B1_TITLE = 'Goethe-Zertifikat B1: Zertifikat Deutsch';
    const COURSE_AND_CERTIFICATE_GOETHE_ZERTIFIKAT_B1_AWARDED = 'Goethe-Institut Minsk';
    const COURSE_AND_CERTIFICATE_GOETHE_ZERTIFIKAT_B1_DATE = '2013-06-19';

    const PROJECT_OASIS_NAME = 'OASIS';
    const PROJECT_OASIS_TECHNOLOGIES = 'Tcl/Tk, C, CarbonLib, SQLite, SOAP';
    const PROJECT_OASIS_OPERATING_SYSTEMS = 'Mac OS X, Linux, Mac OS 9';
    const PROJECT_OASIS_START_DATE = '2006-09-01';
    const PROJECT_OASIS_END_DATE = '2006-12-30';

    const PROJECT_OPFORMA_CLIENT_FOR_MACOS_X10_NAME = 'OpForma Client for MacOS X 10';
    const PROJECT_OPFORMA_CLIENT_FOR_MACOS_X10_TECHNOLOGIES = 'Objective-C, C, Cocoa, CarbonLib, AppleScript, Java';
    const PROJECT_OPFORMA_CLIENT_FOR_MACOS_X10_OPERATING_SYSTEMS = 'MacOS X 10';
    const PROJECT_OPFORMA_CLIENT_FOR_MACOS_X10_START_DATE = '2007-01-01';
    const PROJECT_OPFORMA_CLIENT_FOR_MACOS_X10_END_DATE = '2007-10-30';

    const PROJECT_CDROMTOOL_NAME = 'CDROMTool';
    const PROJECT_CDROMTOOL_TECHNOLOGIES = 'C++, wxWidgets, Metakit';
    const PROJECT_CDROMTOOL_OPERATING_SYSTEMS = 'MacOS X 10';
    const PROJECT_CDROMTOOL_START_DATE = '2007-05-01';
    const PROJECT_CDROMTOOL_END_DATE = '2007-06-30';

    const PROJECT_OASIS_X10_NAME = 'OASIS X10';
    const PROJECT_OASIS_X10_TECHNOLOGIES = 'Tcl/Tk, C, CarbonLib, SQLite, SOAP';
    const PROJECT_OASIS_X10_OPERATING_SYSTEMS = 'MacOS X 10';
    const PROJECT_OASIS_X10_START_DATE = '2007-11-01';
    const PROJECT_OASIS_X10_END_DATE = '2007-12-30';

    const PROJECT_OPFORMA_CLIENT_FOR_MACOS_X10_V20_NAME = 'OpForma Client for MacOS X 10 v2.0';
    const PROJECT_OPFORMA_CLIENT_FOR_MACOS_X10_V20_TECHNOLOGIES = 'Objective-C, C, Cocoa, CarbonLib, AppleScript, Java';
    const PROJECT_OPFORMA_CLIENT_FOR_MACOS_X10_V20_OPERATING_SYSTEMS = 'MacOS X 10';
    const PROJECT_OPFORMA_CLIENT_FOR_MACOS_X10_V20_START_DATE = '2008-01-01';
    const PROJECT_OPFORMA_CLIENT_FOR_MACOS_X10_V20_END_DATE = '2008-02-28';

    const PROJECT_LOTUS_NOTES_APM_NAME = 'Lotus Notes Application Plugin Module';
    const PROJECT_LOTUS_NOTES_APM_TECHNOLOGIES = 'C, NetVault API, Lotus Notes API';
    const PROJECT_LOTUS_NOTES_APM_OPERATING_SYSTEMS = 'Windows 2000/XP/2003, Linux 2.6 kernel';
    const PROJECT_LOTUS_NOTES_APM_START_DATE = '2008-03-01';
    const PROJECT_LOTUS_NOTES_APM_END_DATE = '2008-06-30';

    const PROJECT_VAULTDR_NAME = 'VaultDR';
    const PROJECT_VAULTDR_TECHNOLOGIES = 'C, OpenSSL';
    const PROJECT_VAULTDR_OPERATING_SYSTEMS = 'Linux 2.6 kernel';
    const PROJECT_VAULTDR_START_DATE = '2008-03-15';
    const PROJECT_VAULTDR_END_DATE = '2008-04-30';

    const PROJECT_MYSQL_APM_NAME = 'MySQL Application Plugin Module';
    const PROJECT_MYSQL_APM_TECHNOLOGIES = 'C, NetVault API, MySQL API';
    const PROJECT_MYSQL_APM_OPERATING_SYSTEMS = 'Windows 2000/XP/2003, Linux 2.6 kernel';
    const PROJECT_MYSQL_APM_START_DATE = '2008-05-01';
    const PROJECT_MYSQL_APM_END_DATE = '2008-08-30';

    const PROJECT_ZDHCP_NAME = 'zDHCP';
    const PROJECT_ZDHCP_TECHNOLOGIES = 'Perl';
    const PROJECT_ZDHCP_OPERATING_SYSTEMS = 'Linux 2.6 kernel';
    const PROJECT_ZDHCP_START_DATE = '2008-09-01';
    const PROJECT_ZDHCP_END_DATE = '2008-10-30';

    const PROJECT_VIOM_NAME = 'VIOM';
    const PROJECT_VIOM_TECHNOLOGIES = 'J2SE, Swing, Hibernate, JUnit, MS SQL, PostgreSQL, IPMIlib, Ganymed SSH, Maverick, Quartz';
    const PROJECT_VIOM_OPERATING_SYSTEMS = 'Windows 2003/2008, SLES 10/11, RHEL 5/6';
    const PROJECT_VIOM_START_DATE = '2008-11-01';
    const PROJECT_VIOM_END_DATE = '0000-00-00';

    const PROJECT_SPM_NAME = 'SPM';
    const PROJECT_SPM_TECHNOLOGIES = 'J2EE, Tomcat, Hibernate, Spring, Apache Wicket, Quartz, JUnit, H2database, MS SQL, PostgreSQL, SMNP4j, IPMIlib, WinPCAP, SBLIM CIM Client';
    const PROJECT_SPM_OPERATING_SYSTEMS = 'Windows 2003/2008/7, SLES 10/11, RHEL 5/6';
    const PROJECT_SPM_START_DATE = '2009-12-01';
    const PROJECT_SPM_END_DATE = '2012-09-30';

    const PROJECT_SVOM_NAME = 'SVOM';
    const PROJECT_SVOM_TECHNOLOGIES = 'J2EE, JBoss, Hibernate, JUnit, MS SQL, PostgreSQL, SMNP4j, IPMIlib, SBLIM CIM';
    const PROJECT_SVOM_OPERATING_SYSTEMS = 'Windows 2003/2008/2012, SLES 10/11, RHEL 5/6';
    const PROJECT_SVOM_START_DATE = '2012-08-01';
    const PROJECT_SVOM_END_DATE = '0000-00-00';

    const PROJECT_AGENTS_NAME = 'Agents';
    const PROJECT_AGENTS_TECHNOLOGIES = 'C++, sqlite3, SNMP, SOAP, zlib, virtualization APIs';
    const PROJECT_AGENTS_OPERATING_SYSTEMS = 'VMware ESX Server, Kernel-based Virtual Machine, Microsoft Hyper-V, Citrix XenServer';
    const PROJECT_AGENTS_START_DATE = '2012-10-01';
    const PROJECT_AGENTS_END_DATE = '0000-00-00';

    const I18N_TRANSLATION_VALUE_EMAIL = 'E-mail';
    const I18N_TRANSLATION_VALUE_SKYPE = 'Skype';


    const I18N_TRANSLATION_ID_ONLINE_CV = 0;
    const I18N_TRANSLATION_ID_DOWNLOAD_PDF_VERSION = 1;
    const I18N_TRANSLATION_ID_PERSONAL_INFORMATION = 2;
    const I18N_TRANSLATION_ID_ADDRESS = 3;
    const I18N_TRANSLATION_ID_PHONE = 4;
    const I18N_TRANSLATION_ID_EMAIL = 5;
    const I18N_TRANSLATION_ID_SKYPE = 6;
    const I18N_TRANSLATION_ID_DATE_OF_BIRTH = 7;
    const I18N_TRANSLATION_ID_PLACE_OF_BIRTH = 8;
    const I18N_TRANSLATION_ID_MARITAL_STATUS = 9;
    const I18N_TRANSLATION_ID_HOMEPAGE = 10;
    const I18N_TRANSLATION_ID_EMPLOYMENT_HISTORY = 11;
    const I18N_TRANSLATION_ID_DATE = 12;
    const I18N_TRANSLATION_ID_COMPANY = 13;
    const I18N_TRANSLATION_ID_POSITION = 14;
    const I18N_TRANSLATION_ID_RESPONSIBILITIES = 15;
    const I18N_TRANSLATION_ID_EDUCATION = 16;
    const I18N_TRANSLATION_ID_EDUCATIONAL_INSTITUTION = 17;
    const I18N_TRANSLATION_ID_FACULTY = 18;
    const I18N_TRANSLATION_ID_DEPARTMENT = 19;
    const I18N_TRANSLATION_ID_QUALIFICATION = 20;
    const I18N_TRANSLATION_ID_LANGUAGES = 21;
    const I18N_TRANSLATION_ID_COURSES_AND_CERTIFICATES = 22;
    const I18N_TRANSLATION_ID_TITLE = 23;
    const I18N_TRANSLATION_ID_AWARDED = 24;
    const I18N_TRANSLATION_ID_TECHNICAL_SKILLS = 25;
    const I18N_TRANSLATION_ID_TECHNOLOGY = 26;
    const I18N_TRANSLATION_ID_EXPERIENCE_YEARS = 27;
    const I18N_TRANSLATION_ID_PROFICIENCY = 28;
    const I18N_TRANSLATION_ID_PROJECTS = 29;
    const I18N_TRANSLATION_ID_PROJECT_NAME = 30;
    const I18N_TRANSLATION_ID_PROJECT_DESCRIPTION = 31;
    const I18N_TRANSLATION_ID_PROJECT_DURATION = 32;
    const I18N_TRANSLATION_ID_PRESENT = 33;
    const I18N_TRANSLATION_ID_LANGUAGE_CEFR = 34;
    const I18N_TRANSLATION_ID_LANGUAGE_CEFR_URL = 35;
    const I18N_TRANSLATION_ID_TECHNOLOGIES = 36;
    const I18N_TRANSLATION_ID_OPERATING_SYSTEMS = 37;
    const I18N_TRANSLATION_ID_URL_DOWNLOAD_PDF_VERSION = 38;

    const SKILL_CATEGORY_ID_PROGRAMMING_LANGUAGES = 1;
    const SKILL_CATEGORY_ID_TECHNOLOGIES = 2;
    const SKILL_CATEGORY_ID_OPERATING_SYSTEMS = 3;
    const SKILL_CATEGORY_ID_RDBMSS = 4;
    const SKILL_CATEGORY_ID_WEB_AND_APPLICATION_SERVERS = 5;
    const SKILL_CATEGORY_ID_CASE_AND_PROJECT_TOOLS = 6;
    const SKILL_CATEGORY_ID_IDES = 7;

    const PDF_EXT = '.pdf';
    const DOCX_EXT = '.docx';
}